""""remaned invoice columns"

Revision ID: 6059b83d0ee3
Revises: f28f254abf8f
Create Date: 2025-03-27 20:58:05.068013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6059b83d0ee3'
down_revision = 'f28f254abf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_start', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('date_end', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('date_due', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('price_subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_discount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_total', sa.Float(), nullable=False))
        batch_op.drop_column('discount_price')
        batch_op.drop_column('total_price')
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('subtotal_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('discount_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('price_total')
        batch_op.drop_column('price_discount')
        batch_op.drop_column('price_subtotal')
        batch_op.drop_column('date_due')
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')

    # ### end Alembic commands ###
