""""added updated by to expense"

Revision ID: 78019c1b4dbc
Revises: b4e1a01ae94c
Create Date: 2025-03-29 15:20:34.368756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78019c1b4dbc'
down_revision = 'b4e1a01ae94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['updated_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_by')

    # ### end Alembic commands ###
