""""added user is active field"

Revision ID: b4e1a01ae94c
Revises: 6059b83d0ee3
Create Date: 2025-03-28 14:36:19.169440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e1a01ae94c'
down_revision = '6059b83d0ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('expense_updated_by_fkey', type_='foreignkey')
        batch_op.drop_column('updated_by')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('date_due',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('date_due',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('expense_updated_by_fkey', 'user', ['updated_by'], ['user_id'])

    # ### end Alembic commands ###
