""""updated invoice"

Revision ID: bc5d3a84422d
Revises: a9d01493fae5
Create Date: 2025-03-27 09:45:19.401981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5d3a84422d'
down_revision = 'a9d01493fae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_paid', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=255), nullable=False))
        batch_op.drop_column('is_paid')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('reference')
        batch_op.drop_column('date_paid')

    # ### end Alembic commands ###
