""""changed to discount_price in invoices"

Revision ID: f28f254abf8f
Revises: bc5d3a84422d
Create Date: 2025-03-27 17:52:23.818811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28f254abf8f'
down_revision = 'bc5d3a84422d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=False))
        batch_op.drop_column('total_price_discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price_discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###
